//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPracticeSessionOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Code_Employee { get; set; }
        public string Surname_Employee { get; set; }
        public string Name_Employee { get; set; }
        public string Midname_Employee { get; set; }
        public int Code_Role { get; set; }
        public string Number_Employee { get; set; }
        public string Password_Employee { get; set; }
    
        public virtual Employee_Roles Employee_Roles { get; set; }
    }
}
